export const initialData = [
  {
    "id": "home",
    "name": "Home",
    "order": 1,
    "tools": [
      {"id": "youtube", "name": "Youtube", "url": "https://www.youtube.com/", "icon": "fab fa-youtube", "order": 1, "category": "home"},
      {"id": "gmail", "name": "Gmail", "url": "https://mail.google.com/", "icon": "fas fa-envelope", "order": 2, "category": "home"},
      {"id": "github", "name": "GitHub", "url": "https://github.com/", "icon": "fab fa-github", "order": 3, "category": "home"},
      {"id": "ip-sb", "name": "ip.sb", "url": "https://ip.sb/", "icon": "fas fa-network-wired", "order": 4, "category": "home"},
      {"id": "cloudflare", "name": "Cloudflare", "url": "https://dash.cloudflare.com/", "icon": "fas fa-cloud", "order": 5, "category": "home"},
      {"id": "节点订阅器", "name": "节点订阅器", "url": "https://eooce.qzz.io/", "icon": "fas fa-rss-square", "order": 6, "category": "home"},
      {"id": "huggingface", "name": "Huggingface", "url": "https://huggingface.co/", "icon": "fas fa-brain", "order": 7, "category": "home"},
      {"id": "itdog", "name": "ITDOG - 在线ping", "url": "https://www.itdog.cn/ping/", "icon": "fas fa-server", "order": 8, "category": "home"},
      {"id": "ping0", "name": "Ping0", "url": "https://ping0.cc/", "icon": "fas fa-tachometer-alt", "order": 9, "category": "home"},
      {"id": "浏览器指纹", "name": "浏览器指纹", "url": "https://www.browserscan.net/zh", "icon": "fas fa-fingerprint", "order": 10, "category": "home"},
      {"id": "nezha面板", "name": "nezha面板", "url": "https://ssss.nyc.mn/", "icon": "fas fa-chart-line", "order": 11, "category": "home"},
      {"id": "api-test", "name": "API测试", "url": "https://hoppscotch.io/", "icon": "fas fa-flask", "order": 12, "category": "home"},
      {"id": "域名检查", "name": "域名检查", "url": "https://who.cx/", "icon": "fas fa-globe-americas", "order": 13, "category": "home"},
      {"id": "域名比价", "name": "域名比价", "url": "https://www.nazhumi.com/", "icon": "fas fa-money-check-alt", "order": 14, "category": "home"},
      {"id": "nodesseek", "name": "Nodesseek", "url": "https://www.nodesseek.com/", "icon": "fas fa-search-location", "order": 15, "category": "home"},
      {"id": "linux-do", "name": "Linux do", "url": "https://linux.do/", "icon": "fab fa-linux", "order": 16, "category": "home"},
      {"id": "在线音乐", "name": "在线音乐", "url": "https://music.eooce.com/", "icon": "fas fa-music", "order": 17, "category": "home"},
      {"id": "nodeloc", "name": "Nodeloc", "url": "https://www.nodeloc.com/", "icon": "fas fa-map-marker-alt", "order": 18, "category": "home"},
      {"id": "免费接码", "name": "免费接码", "url": "https://www.freereceivesms.com/", "icon": "fas fa-sms", "order": 19, "category": "home"},
      {"id": "订阅转换", "name": "订阅转换", "url": "https://sublink.eooce.com/", "icon": "fas fa-sync-alt", "order": 20, "category": "home"},
      {"id": "webssh", "name": "webssh", "url": "https://ssh.eooce.com/", "icon": "fas fa-terminal", "order": 21, "category": "home"},
      {"id": "文件快速柜", "name": "文件快速柜", "url": "https://filebox.nnuu.nyc.mn/#/", "icon": "fas fa-inbox", "order": 22, "category": "home"},
      {"id": "真实地址生成", "name": "真实地址生成", "url": "https://address.nnuu.nyc.mn/", "icon": "fas fa-address-card", "order": 23, "category": "home"}
    ]
  },
  {
    "id": "ai-stuff",
    "name": "AI-stuff",
    "order": 2,
    "tools": [
      {"id": "chatgpt", "name": "ChatGPT", "url": "https://chat.openai.com/", "icon": "fas fa-robot", "order": 1, "category": "ai-stuff"},
      {"id": "claude", "name": "Claude", "url": "https://claude.ai/", "icon": "fas fa-cloud", "order": 2, "category": "ai-stuff"},
      {"id": "deepseek", "name": "Deepseek", "url": "https://www.deepseek.com/", "icon": "fas fa-search", "order": 3, "category": "ai-stuff"},
      {"id": "google-gemini", "name": "Google Gemini", "url": "https://gemini.google.com/", "icon": "fas fa-gem", "order": 4, "category": "ai-stuff"},
      {"id": "阿里千问", "name": "阿里千问", "url": "https://chat.qwen.ai/", "icon": "fas fa-brain", "order": 5, "category": "ai-stuff"},
      {"id": "kimi", "name": "Kimi", "url": "https://kimi.moonshot.cn/", "icon": "fas fa-rocket", "order": 6, "category": "ai-stuff"},
      {"id": "问小白", "name": "问小白", "url": "https://www.wenxiaobai.com/", "icon": "fas fa-question", "order": 7, "category": "ai-stuff"},
      {"id": "genspark", "name": "Genspark", "url": "https://www.genspark.ai/agents?type=moa_chat", "icon": "fas fa-sparkles", "order": 8, "category": "ai-stuff"},
      {"id": "akashchat", "name": "AkashChat", "url": "https://chat.akash.network/", "icon": "fas fa-comments", "order": 9, "category": "ai-stuff"},
      {"id": "v0", "name": "V0", "url": "https://v0.app/chat", "icon": "fas fa-code", "order": 10, "category": "ai-stuff"},
      {"id": "same", "name": "Same", "url": "https://same.new/", "icon": "fas fa-clone", "order": 11, "category": "ai-stuff"},
      {"id": "haisnap", "name": "响指HaiSnap", "url": "https://www.haisnap.com/", "icon": "fas fa-fingerprint", "order": 12, "category": "ai-stuff"},
      {"id": "readdy", "name": "Readdy", "url": "https://readdy.ai/", "icon": "fas fa-lightbulb", "order": 13, "category": "ai-stuff"},
      {"id": "openrouter", "name": "Openrouter", "url": "https://openrouter.ai/", "icon": "fas fa-server", "order": 14, "category": "ai-stuff"},
      {"id": "manus", "name": "Manus", "url": "https://manus.im/", "icon": "fas fa-hand-paper", "order": 15, "category": "ai-stuff"},
      {"id": "perplexity", "name": "Perplexity", "url": "https://www.perplexity.ai/", "icon": "fas fa-question-circle", "order": 16, "category": "ai-stuff"},
      {"id": "grok", "name": "Grok", "url": "https://grok.com/", "icon": "fas fa-brain", "order": 17, "category": "ai-stuff"},
      {"id": "copilot", "name": "Copilot", "url": "https://copilot.microsoft.com/", "icon": "fab fa-microsoft", "order": 18, "category": "ai-stuff"},
      {"id": "豆包", "name": "豆包", "url": "https://www.doubao.com/", "icon": "fas fa-seedling", "order": 19, "category": "ai-stuff"},
      {"id": "文心一言", "name": "文心一言", "url": "https://yiyan.baidu.com/", "icon": "fas fa-comment-dots", "order": 20, "category": "ai-stuff"},
      {"id": "jules", "name": "Jules", "url": "https://jules.google.com/task", "icon": "fab fa-google", "order": 21, "category": "ai-stuff"},
      {"id": "硅基流动", "name": "硅基流动", "url": "https://account.siliconflow.cn/zh/login?redirect=https%3A%2F%2Fcloud.siliconflow.cn%2F%3F", "icon": "fas fa-chart-network", "order": 22, "category": "ai-stuff"},
      {"id": "kilocode", "name": "Kilo Code", "url": "https://kilocode.ai/", "icon": "fas fa-code-branch", "order": 23, "category": "ai-stuff"},
      {"id": "cursor", "name": "Cursor", "url": "https://www.cursor.com/", "icon": "fas fa-pen-nib", "order": 24, "category": "ai-stuff"},
      {"id": "ai一键换脸", "name": "AI一键换脸", "url": "https://imgai.ai/zh", "icon": "fas fa-magic", "order": 25, "category": "ai-stuff"},
      {"id": "alppt", "name": "Alppt", "url": "https://www.aippt.cn/", "icon": "fas fa-file-powerpoint", "order": 26, "category": "ai-stuff"},
      {"id": "ai照片修复", "name": "AI照片修复", "url": "https://picwish.cn/photo-enhancer", "icon": "fas fa-image", "order": 27, "category": "ai-stuff"},
      {"id": "bolt", "name": "Bolt", "url": "https://bolt.new/", "icon": "fas fa-bolt", "order": 28, "category": "ai-stuff"},
      {"id": "llamacoder", "name": "Llamacoder", "url": "https://llamacoder.together.ai/", "icon": "fas fa-terminal", "order": 29, "category": "ai-stuff"},
      {"id": "codia", "name": "Codia", "url": "https://codia.ai/", "icon": "fas fa-feather-alt", "order": 30, "category": "ai-stuff"}
    ]
  },
  {
    "id": "cloud",
    "name": "Cloud",
    "order": 3,
    "tools": [
      {"id": "阿里云", "name": "阿里云", "url": "https://www.aliyun.com/", "icon": "fas fa-cloud", "order": 1, "category": "cloud"},
      {"id": "腾讯云", "name": "腾讯云", "url": "https://cloud.tencent.com/", "icon": "fas fa-cloud", "order": 2, "category": "cloud"},
      {"id": "甲骨文云", "name": "甲骨文云", "url": "https://www.oracle.com/cloud/", "icon": "fas fa-cloud", "order": 3, "category": "cloud"},
      {"id": "亚马逊云", "name": "亚马逊云", "url": "https://aws.amazon.com/", "icon": "fab fa-aws", "order": 4, "category": "cloud"},
      {"id": "digitalocean", "name": "DigitalOcean", "url": "https://www.digitalocean.com/", "icon": "fas fa-cloud", "order": 5, "category": "cloud"},
      {"id": "vultr", "name": "Vultr", "url": "https://www.vultr.com/", "icon": "fas fa-cloud", "order": 6, "category": "cloud"},
      {"id": "谷歌云", "name": "谷歌云", "url": "https://cloud.google.com/", "icon": "fab fa-google", "order": 7, "category": "cloud"},
      {"id": "azure", "name": "Azure", "url": "https://azure.microsoft.com/", "icon": "fab fa-microsoft", "order": 8, "category": "cloud"},
      {"id": "linode", "name": "Linode", "url": "https://www.linode.com/", "icon": "fas fa-cloud", "order": 9, "category": "cloud"},
      {"id": "cloudcone", "name": "Cloudcone", "url": "https://app.cloudcone.com/", "icon": "fas fa-cloud", "order": 10, "category": "cloud"},
      {"id": "dartnode", "name": "Dartnode", "url": "https://dartnode.com/", "icon": "fas fa-cloud", "order": 11, "category": "cloud"},
      {"id": "dmit", "name": "DMIT", "url": "https://www.dmit.io/", "icon": "fas fa-cloud", "order": 12, "category": "cloud"},
      {"id": "bandwagonhost", "name": "Bandwagonhost", "url": "https://bandwagonhost.com/", "icon": "fas fa-cloud", "order": 13, "category": "cloud"},
      {"id": "racknerd", "name": "Racknerd", "url": "https://racknerd.com/", "icon": "fas fa-cloud", "order": 14, "category": "cloud"},
      {"id": "atlantic", "name": "Atlantic", "url": "https://cloud.atlantic.net/?page=userlogin", "icon": "fas fa-cloud", "order": 15, "category": "cloud"},
      {"id": "lightnode", "name": "Lightnode", "url": "https://www.lightnode.com/", "icon": "fas fa-cloud", "order": 16, "category": "cloud"},
      {"id": "ishosting", "name": "Ishosting", "url": "https://www.ishosting.com/", "icon": "fas fa-cloud", "order": 17, "category": "cloud"},
      {"id": "diylink", "name": "Diylink", "url": "https://console.diylink.net/login", "icon": "fas fa-cloud", "order": 18, "category": "cloud"},
      {"id": "ibm", "name": "IBM", "url": "https://www.ibm.com/cloud", "icon": "fas fa-cloud", "order": 19, "category": "cloud"},
      {"id": "sharon", "name": "Sharon", "url": "https://whmcs.sharon.io/", "icon": "fas fa-cloud", "order": 20, "category": "cloud"},
      {"id": "alice", "name": "Alice", "url": "https://alicenetworks.net/", "icon": "fas fa-cloud", "order": 21, "category": "cloud"},
      {"id": "yxvm", "name": "Yxvm", "url": "https://yxvm.com/", "icon": "fas fa-cloud", "order": 22, "category": "cloud"},
      {"id": "cloudforest", "name": "Cloudforest", "url": "https://cloud.cloudforest.ro/", "icon": "fas fa-cloud", "order": 23, "category": "cloud"},
      {"id": "华为云", "name": "华为云", "url": "https://www.huaweicloud.com/", "icon": "fas fa-cloud", "order": 24, "category": "cloud"}
    ]
  },
  {
    "id": "container",
    "name": "Container",
    "order": 4,
    "tools": [
      {"id": "koyeb", "name": "Koyeb", "url": "https://app.koyeb.com/", "icon": "fas fa-box", "order": 1, "category": "container"},
      {"id": "render", "name": "Render", "url": "https://render.com/", "icon": "fas fa-box", "order": 2, "category": "container"},
      {"id": "fly", "name": "Fly", "url": "https://fly.io/", "icon": "fas fa-plane", "order": 3, "category": "container"},
      {"id": "northflank", "name": "Northflank", "url": "https://app.northflank.com/", "icon": "fas fa-box", "order": 4, "category": "container"},
      {"id": "choreo", "name": "Choreo", "url": "https://console.choreo.dev/", "icon": "fas fa-box", "order": 5, "category": "container"},
      {"id": "railway", "name": "Railway", "url": "https://railway.app/", "icon": "fas fa-train", "order": 6, "category": "container"},
      {"id": "galaxycloud", "name": "Galaxycloud", "url": "https://beta.galaxycloud.app/", "icon": "fas fa-galaxy", "order": 7, "category": "container"},
      {"id": "azure-container", "name": "Azure容器", "url": "https://azure.microsoft.com/products/container-instances/", "icon": "fab fa-microsoft", "order": 8, "category": "container"},
      {"id": "codered", "name": "Codered", "url": "https://app.codered.cloud/login/?next=/hosting/webapps/app", "icon": "fas fa-box", "order": 9, "category": "container"},
      {"id": "shuttle", "name": "Shuttle", "url": "https://console.shuttle.dev/login", "icon": "fas fa-shuttle-space", "order": 10, "category": "container"},
      {"id": "serv00", "name": "Serv00", "url": "https://www.serv00.com/", "icon": "fas fa-box", "order": 11, "category": "container"},
      {"id": "ct8", "name": "CT8", "url": "https://www.ct8.pl/", "icon": "fas fa-box", "order": 12, "category": "container"},
      {"id": "claw", "name": "Claw", "url": "https://us-west-1.run.claw.cloud/signin", "icon": "fas fa-box", "order": 13, "category": "container"},
      {"id": "cloudcat", "name": "Cloudcat", "url": "https://cloud.cloudcat.one/", "icon": "fas fa-cat", "order": 14, "category": "container"},
      {"id": "huggingface-container", "name": "Huggingface", "url": "https://huggingface.co/", "icon": "fas fa-brain", "order": 15, "category": "container"},
      {"id": "alwaysdata", "name": "Alwaysdata", "url": "https://admin.alwaysdata.com/login/?next=/", "icon": "fas fa-box", "order": 16, "category": "container"},
      {"id": "vercel", "name": "Vercel", "url": "https://vercel.com/", "icon": "fas fa-box", "order": 17, "category": "container"},
      {"id": "netlify", "name": "Netlify", "url": "https://www.netlify.com/", "icon": "fas fa-box", "order": 18, "category": "container"},
      {"id": "modal", "name": "Modal", "url": "https://modal.com/", "icon": "fas fa-box", "order": 19, "category": "container"},
      {"id": "scalingo", "name": "Scalingo", "url": "https://scalingo.com/", "icon": "fas fa-box", "order": 20, "category": "container"},
      {"id": "sevalla", "name": "Sevalla", "url": "https://app.sevalla.com/", "icon": "fas fa-box", "order": 21, "category": "container"},
      {"id": "phala", "name": "Phala", "url": "https://phala.com/", "icon": "fas fa-box", "order": 22, "category": "container"},
      {"id": "wasmer", "name": "Wasmer", "url": "https://wasmer.io/", "icon": "fas fa-box", "order": 23, "category": "container"},
      {"id": "appwrite", "name": "Appwrite", "url": "https://cloud.appwrite.io/console", "icon": "fas fa-box", "order": 24, "category": "container"}
    ]
  },
  {
    "id": "software",
    "name": "Software",
    "order": 5,
    "tools": [
      {"id": "hellowindows", "name": "Hellowindows", "url": "https://hellowindows.cn/", "icon": "fab fa-windows", "order": 1, "category": "software"},
      {"id": "云萌win10-11激活", "name": "云萌Win10/11激活", "url": "https://cmwtat.cloudmoe.com/cn.html", "icon": "fab fa-windows", "order": 2, "category": "software"},
      {"id": "lxmusic", "name": "LXmusic", "url": "https://lxmusic.toside.cn/", "icon": "fas fa-music", "order": 3, "category": "software"},
      {"id": "geek-uninstaller", "name": "Geek Uninstaller", "url": "https://geekuninstaller.com/", "icon": "fas fa-trash", "order": 4, "category": "software"},
      {"id": "奇迹秀", "name": "奇迹秀", "url": "https://www.qijishow.com/down/", "icon": "fas fa-magic", "order": 5, "category": "software"},
      {"id": "zen-browser", "name": "Zen-browser", "url": "https://zen-browser.app/", "icon": "fas fa-browser", "order": 6, "category": "software"},
      {"id": "uu远程", "name": "UU远程", "url": "https://uuyc.163.com/", "icon": "fas fa-desktop", "order": 7, "category": "software"},
      {"id": "pixpin", "name": "Pixpin", "url": "https://pixpin.cn/", "icon": "fas fa-camera", "order": 8, "category": "software"},
      {"id": "mem-reduct", "name": "Mem Reduct", "url": "https://github.com/henrypp/memreduct/releases/tag/v.3.5.2", "icon": "fas fa-memory", "order": 9, "category": "software"},
      {"id": "易破解", "name": "易破解", "url": "https://www.ypojie.com/", "icon": "fas fa-lock-open", "order": 10, "category": "software"},
      {"id": "adspower", "name": "Adspower", "url": "https://activity.adspower.com/ap/dist/", "icon": "fas fa-power-off", "order": 11, "category": "software"},
      {"id": "qtscrcpy", "name": "QtScrcpy", "url": "https://github.com/barry-ran/QtScrcpy/releases/tag/v3.3.1", "icon": "fas fa-mobile-alt", "order": 12, "category": "software"},
      {"id": "cracked-software", "name": "Cracked Software", "url": "https://topcracked.com/", "icon": "fas fa-code", "order": 13, "category": "software"},
      {"id": "termora", "name": "Termora", "url": "https://www.termora.app/downloads", "icon": "fas fa-terminal", "order": 14, "category": "software"},
      {"id": "小丸工具箱", "name": "小丸工具箱", "url": "https://maruko.appinn.me/", "icon": "fas fa-toolbox", "order": 15, "category": "software"},
      {"id": "phpstudy", "name": "phpstudy", "url": "https://www.xp.cn/phpstudy", "icon": "fab fa-php", "order": 16, "category": "software"},
      {"id": "cherry-studio", "name": "Cherry Studio", "url": "https://www.cherry-ai.com/", "icon": "fas fa-brain", "order": 17, "category": "software"},
      {"id": "beekeeper-studio", "name": "Beekeeper studio", "url": "https://www.beekeeperstudio.io/", "icon": "fas fa-database", "order": 18, "category": "software"},
      {"id": "requestly", "name": "Requestly", "url": "https://requestly.com/", "icon": "fas fa-link", "order": 19, "category": "software"},
      {"id": "navicat-premium", "name": "Navicat Premium", "url": "https://www.navicat.com/", "icon": "fas fa-database", "order": 20, "category": "software"},
      {"id": "incognition", "name": "Incognition", "url": "https://incogniton.com/zh-hans/", "icon": "fas fa-user-secret", "order": 21, "category": "software"},
      {"id": "musicfree", "name": "MusicFree", "url": "https://musicfree.catcat.work/", "icon": "fas fa-music", "order": 22, "category": "software"},
      {"id": "raylink", "name": "Raylink", "url": "https://www.raylink.live/", "icon": "fas fa-link", "order": 23, "category": "software"},
      {"id": "v2rayn", "name": "VZrayN（V2rayN）", "url": "https://v2rayn.2dust.link/", "icon": "fas fa-link", "order": 24, "category": "software"},
      {"id": "mihomo-party", "name": "Mihomo Party", "url": "https://clashparty.org/", "icon": "fas fa-link", "order": 25, "category": "software"},
      {"id": "gui-for-singbox", "name": "GUI.for.SingBox", "url": "https://github.com/GUI-for-Cores/GUI.for.SingBox/releases/tag/v1.10.0", "icon": "fas fa-link", "order": 26, "category": "software"},
      {"id": "ficlash", "name": "FiClash", "url": "https://github.com/chen08209/FlClash/releases/tag/v0.8.87", "icon": "fas fa-link", "order": 27, "category": "software"},
      {"id": "karing", "name": "Karing", "url": "https://karing.app/download/", "icon": "fas fa-link", "order": 28, "category": "software"},
      {"id": "nekobox", "name": "Nekobox", "url": "https://nekobox.tools/nekoray/", "icon": "fas fa-link", "order": 29, "category": "software"},
      {"id": "flyclash", "name": "FlyClash", "url": "https://github.com/GtxFury/FlyClash/releases/tag/v0.1.6", "icon": "fas fa-link", "order": 30, "category": "software"},
      {"id": "clashbox", "name": "ClashBox", "url": "https://github.com/xiaobaigroup/ClashBox", "icon": "fas fa-link", "order": 31, "category": "software"}
    ]
  },
  {
    "id": "tools",
    "name": "Tools",
    "order": 6,
    "tools": [
      {"id": "argo-tunnel-json获取", "name": "Argo Tunnel json获取", "url": "https://fscarmen.cloudflare.now.cc/", "icon": "fas fa-file-alt", "order": 1, "category": "tools"},
      {"id": "base64工具", "name": "base64工具", "url": "https://www.qqxiuzi.cn/bianma/base64.htm", "icon": "fas fa-tools", "order": 2, "category": "tools"},
      {"id": "二维码生成", "name": "二维码生成", "url": "https://cli.im/", "icon": "fas fa-qrcode", "order": 3, "category": "tools"},
      {"id": "js混淆", "name": "JS混淆", "url": "https://obfuscator.io/", "icon": "fas fa-code", "order": 4, "category": "tools"},
      {"id": "python混淆", "name": "Python混淆", "url": "https://freecodingtools.org/tools/obfuscator/python", "icon": "fab fa-python", "order": 5, "category": "tools"},
      {"id": "remove-photos", "name": "Remove,photos", "url": "https://remove.photos/zh-cn/", "icon": "fas fa-image", "order": 6, "category": "tools"},
      {"id": "pagespeed", "name": "Pagespeed", "url": "https://pagespeed.web.dev/", "icon": "fas fa-tachometer-alt", "order": 7, "category": "tools"},
      {"id": "自动访问", "name": "自动访问", "url": "https://keep.gvrander.eu.org/", "icon": "fas fa-link", "order": 8, "category": "tools"},
      {"id": "cron-job", "name": "Cron-job", "url": "https://cron-job.org/", "icon": "fas fa-clock", "order": 9, "category": "tools"},
      {"id": "网址缩短", "name": "网址缩短", "url": "https://short.ssss.nyc.mn/", "icon": "fas fa-link", "order": 10, "category": "tools"},
      {"id": "linuxmirrors", "name": "Linuxmirrors", "url": "https://linuxmirrors.cn/", "icon": "fab fa-linux", "order": 11, "category": "tools"},
      {"id": "vocalremover", "name": "Vocalremover", "url": "https://vocalremover.org/", "icon": "fas fa-microphone", "order": 12, "category": "tools"},
      {"id": "json工具", "name": "JSON工具", "url": "https://www.json.cn/", "icon": "fas fa-code", "order": 13, "category": "tools"},
      {"id": "文件格式转换", "name": "文件格式转换", "url": "https://convertio.co/zh/", "icon": "fas fa-exchange-alt", "order": 14, "category": "tools"},
      {"id": "视频在线下载", "name": "视频在线下载", "url": "https://tubedown.cn/youtube", "icon": "fas fa-download", "order": 15, "category": "tools"},
      {"id": "it-tools", "name": "it tools", "url": "https://it.idev.dev/", "icon": "fas fa-tools", "order": 16, "category": "tools"},
      {"id": "emoji大全", "name": "emoji大全", "url": "https://www.iamwawa.cn/emoji.html", "icon": "fas fa-grin-stars", "order": 17, "category": "tools"},
      {"id": "信用卡生成", "name": "信用卡生成", "url": "https://bincheck.io/zh/credit-card-generator", "icon": "fas fa-credit-card", "order": 18, "category": "tools"},
      {"id": "squoosh", "name": "Squoosh", "url": "https://squoosh.app/", "icon": "fas fa-compress", "order": 19, "category": "tools"},
      {"id": "tool", "name": "Tool", "url": "https://tool.lu/", "icon": "fas fa-toolbox", "order": 20, "category": "tools"},
      {"id": "dltools", "name": "Dltools（D1tools）", "url": "https://d1tools.com/", "icon": "fas fa-tools", "order": 21, "category": "tools"},
      {"id": "lumiproxy", "name": "Lumiproxy", "url": "https://www.lumiproxy.com/zh-hans/online-proxy/proxysite/", "icon": "fas fa-globe", "order": 22, "category": "tools"},
      {"id": "proxyshare", "name": "Proxyshare", "url": "https://www.proxyshare.com/zh/proxysite", "icon": "fas fa-share-alt", "order": 23, "category": "tools"},
      {"id": "dnsleaktest", "name": "Dnsleaktest", "url": "https://www.dnsleaktest.com/", "icon": "fas fa-shield-alt", "order": 24, "category": "tools"},
      {"id": "deobfuscator", "name": "Deobfuscator", "url": "https://raz1ner.com/Online-Tools/JavaScript-Deobfuscator.html", "icon": "fas fa-code", "order": 25, "category": "tools"},
      {"id": "flexclip", "name": "flexclip", "url": "https://www.flexclip.com/cn/ai/", "icon": "fas fa-video", "order": 26, "category": "tools"},
      {"id": "星空音乐下载", "name": "星空音乐下载", "url": "https://www.vh.hk/", "icon": "fas fa-music", "order": 27, "category": "tools"},
      {"id": "blackace", "name": "Blackace", "url": "https://blackace.app/", "icon": "fas fa-mask", "order": 28, "category": "tools"},
      {"id": "php混淆加密", "name": "PHP混淆加密", "url": "https://www.toolnb.com/tools/phpcarbylamine.html", "icon": "fab fa-php", "order": 29, "category": "tools"}
    ]
  },
  {
    "id": "mail-domain",
    "name": "Mail & Domain",
    "order": 7,
    "tools": [
      {"id": "gmail", "name": "Gmail", "url": "https://mail.google.com/", "icon": "fas fa-envelope", "order": 1, "category": "mail-domain"},
      {"id": "outlook", "name": "Outlook", "url": "https://outlook.live.com/", "icon": "fas fa-envelope", "order": 2, "category": "mail-domain"},
      {"id": "proton-mail", "name": "Proton Mail", "url": "https://mail.proton.me/", "icon": "fas fa-envelope", "order": 3, "category": "mail-domain"},
      {"id": "qq邮箱", "name": "QQ邮箱", "url": "https://mail.qq.com/", "icon": "fas fa-envelope", "order": 4, "category": "mail-domain"},
      {"id": "雅虎邮箱", "name": "雅虎邮箱", "url": "https://mail.yahoo.com/", "icon": "fas fa-envelope", "order": 5, "category": "mail-domain"},
      {"id": "10分钟临时邮箱", "name": "10分钟临时邮箱", "url": "https://linshiyouxiang.net/", "icon": "fas fa-clock", "order": 6, "category": "mail-domain"},
      {"id": "2925无限邮箱", "name": "2925无限邮箱", "url": "https://www.2925.com/", "icon": "fas fa-infinity", "order": 7, "category": "mail-domain"},
      {"id": "网易vip邮箱", "name": "网易vip邮箱", "url": "https://vip.163.com/", "icon": "fas fa-envelope", "order": 8, "category": "mail-domain"},
      {"id": "88完美邮箱", "name": "88完美邮箱", "url": "https://mail.88.com/mail/#/home", "icon": "fas fa-envelope", "order": 9, "category": "mail-domain"},
      {"id": "临时edu邮箱", "name": "临时edu邮箱", "url": "https://tempmail.edu.kg/", "icon": "fas fa-graduation-cap", "order": 10, "category": "mail-domain"},
      {"id": "tempmail", "name": "Tempmail", "url": "https://tempmail.plus/zh/", "icon": "fas fa-envelope", "order": 11, "category": "mail-domain"},
      {"id": "临时邮箱", "name": "临时邮箱", "url": "https://22.do/zh", "icon": "fas fa-envelope", "order": 12, "category": "mail-domain"},
      {"id": "nyc-mn域名", "name": "nyc.mn域名", "url": "https://dot.nyc.mn/my-domain/", "icon": "fas fa-globe", "order": 13, "category": "mail-domain"},
      {"id": "hidns", "name": "HIDNS", "url": "https://www.hidoha.net/", "icon": "fas fa-dns", "order": 14, "category": "mail-domain"},
      {"id": "dpdns域名", "name": "dpdns域名", "url": "https://dash.domain.digitalplat.org/", "icon": "fas fa-globe", "order": 15, "category": "mail-domain"},
      {"id": "153", "name": "153", "url": "https://customer.l53.net/", "icon": "fas fa-globe", "order": 16, "category": "mail-domain"},
      {"id": "mffac临时邮箱", "name": "mffac临时邮箱", "url": "https://www.mffac.com/", "icon": "fas fa-envelope", "order": 17, "category": "mail-domain"},
      {"id": "zabc-net", "name": "zabc.net", "url": "https://zoneabc.net/dashboard", "icon": "fas fa-globe", "order": 18, "category": "mail-domain"},
      {"id": "eu-org", "name": "eu.org", "url": "https://nic.eu.org/", "icon": "fas fa-globe", "order": 19, "category": "mail-domain"},
      {"id": "zone-id", "name": "zone.id", "url": "https://my.zone.id/subdomains", "icon": "fas fa-globe", "order": 20, "category": "mail-domain"},
      {"id": "spaceship", "name": "Spaceship", "url": "https://spaceship.com/", "icon": "fas fa-space-shuttle", "order": 21, "category": "mail-domain"},
      {"id": "dynadot", "name": "Dynadot", "url": "https://www.dynadot.com/", "icon": "fas fa-globe", "order": 22, "category": "mail-domain"},
      {"id": "godaddy", "name": "Godaddy", "url": "https://www.godaddy.com/", "icon": "fas fa-globe", "order": 23, "category": "mail-domain"},
      {"id": "namesilo", "name": "Namesilo", "url": "https://www.namesilo.com/", "icon": "fas fa-globe", "order": 24, "category": "mail-domain"}
    ]
  },
  {
    "id": "dev",
    "name": "Dev",
    "order": 8,
    "tools": [
      {"id": "igoutu", "name": "igoutu", "url": "https://igoutu.cn/icons", "icon": "fas fa-icons", "order": 1, "category": "dev"},
      {"id": "iconfont", "name": "iconfont", "url": "https://www.iconfont.cn/", "icon": "fas fa-icons", "order": 2, "category": "dev"},
      {"id": "vueform", "name": "vueform", "url": "https://vueform.com/", "icon": "fab fa-vuejs", "order": 3, "category": "dev"},
      {"id": "ghproxy", "name": "ghproxy", "url": "https://ghproxy.eooce.xx.kg/", "icon": "fab fa-github", "order": 4, "category": "dev"},
      {"id": "uiverse", "name": "uiverse", "url": "https://uiverse.io/elements", "icon": "fas fa-rocket", "order": 5, "category": "dev"},
      {"id": "vitepress", "name": "vitepress", "url": "https://vitepress.dev/", "icon": "fas fa-feather-alt", "order": 6, "category": "dev"}
    ]
  }
];
